# Generated by Django 3.0.8 on 2021-03-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='pics',
            field=models.FileField(blank=True, null=True, upload_to='static/'),
        ),
    ]
