# Generated by Django 3.0.8 on 2021-03-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20210313_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='pics',
            field=models.FileField(blank=True, null=True, upload_to='image/'),
        ),
    ]
